# Generated by Django 3.2.4 on 2021-07-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_barrio', models.CharField(max_length=60)),
                ('siglas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60)),
                ('valor_bien', models.IntegerField()),
                ('num_cuarto', models.IntegerField()),
                ('valor_mensual', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barriodepa', to='administrativo.barrio')),
                ('propietario_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personadepartamento', to='administrativo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60)),
                ('valor_bien', models.IntegerField()),
                ('color_inmueble', models.CharField(max_length=20)),
                ('num_cuarto', models.IntegerField()),
                ('num_pisos', models.IntegerField()),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrioscasa', to='administrativo.barrio')),
                ('propietario_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personacasa', to='administrativo.persona')),
            ],
        ),
    ]
