# Generated by Django 3.0.1 on 2021-12-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=60)),
                ('fecha', models.CharField(max_length=15)),
                ('hora', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('velocidad', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='casa',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='propietario_nombre',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='propietario_nombre',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
